### ISSUE TITLE
Failure in CI job

### ISSUE THREAD

**Issue by FredAdiv** [OSDC-Code-Maven/osdc-2023-03-azrieli#23]
Hi everyone, 
I just got an email from github about CI job failure regarding a new post that I have added to my profile JSON.
Can anyone see what's wrong in pull request #22 (7832601382)?
BTW, where can I see that update file that was not committed so I can try to fix it?
Thanks, 
Freddy

**Comment by szabgab** [comment]
IMHO This is not really a good use of the issue-system, but I'd like to applaud that you tried and that you mentioned the PR that had the issue.

**Comment by FredAdiv** [comment]
Found the problem (thnaks to @szabgab).
When adding a post from dev.to, no title or date attributes should be added.

**Comment by FredAdiv** [comment]
Found the problem (thnaks to @szabgab).
When adding a post from dev.to, no title or date attributes should be added.
